[package]
edition = "2024"
name    = "rsshader_macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote       = "1.0.41"
syn         = { version = "2.0.108", features = ["full"] }
